name: tester
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests
  - beautifulsoup4
  - lxml
  - validators
  - dnspython
  - reportlab
  - pip:
    - sslyze>=6.0.0
